### ISSUE TITLE
kDrive AppImage fails to start - "Unable to open parameters database" error

### ISSUE THREAD

**Issue by wvrossem** [Infomaniak/desktop-kDrive#237] opened 2024-08-04 07:15 UTC
I am experiencing an issue when attempting to start the kDrive AppImage on my system. The application fails to initialize properly and presents the following error message when ran via the command line:

    kDrive server starting
    kDrive server initialization error: Unable to open parameters database.

Details:

    AppImage Version: kDrive-3.6.1.20240604-amd64.AppImage
    Operating System: TUXEDO OS 3 x86_64

Additional Information:

    I have verified that my system has the necessary permissions to execute the AppImage.
    Other AppImages ran without issues on this system (version 3.5.8).

**Comment by ClementKunz** [comment] 2024-08-05 09:41
Hi @wvrossem,
Thanks for the report. Indeed it looks like there is an issue with the migration of the database. This will be fixed in the version 3.6.3 to be published soon.
In the meantime, you can still use the 3.5.8.
Regards

**Comment by herve-er** [comment] 2024-08-05 13:06
https://github.com/Infomaniak/desktop-kDrive/pull/197/commits/bba3683dd0c2fea381b260a39f50bcdc19ab56bb

**Comment by JorisBodin** [comment] 2024-08-20 15:29
In prod: 3.6.4

**Comment by nonameuser-de** [comment] 2024-08-24 08:57
It still happens in 3.6.4, same error as above
(3.6.1 worked well)
Kind regards
Arne
Linux Mint 21.3 Virginia 64-bit
Kernel Linux 6.8.0-40-generic x86_64
Intel® Celeron(R) J4105 CPU @ 1.50GHz × 4

**Comment by nonameuser-de** [comment] 2024-08-24 09:29
A work around  :
Delete the /home/<user>/.config/kDrive
Start the AppImage and set up a new connection with the  cloud, make sure to use the same local path (whre the synced files are already)  -After a few seconds the new database is there and everything works fine

**Comment by gaber-IT** [comment] 2024-09-13 09:33
I can confirm issue is still present with 3.6.4 AppImage file.
Please, reopen this issue and keep it open until fixed.

**Comment by pascalm7** [comment] 2024-09-13 10:33
As instructed by [nonameuser-d](https://github.com/nonameuser-de), Removed /home/<username>/.config/kDrive as well as /tmp/kDrive-logdir
Starting the Appimage produces an error message "kDrive application will close due to a fatal error." <OK>

Error log: [20240913_1227_kDrive.log](https://github.com/user-attachments/files/16992521/20240913_1227_kDrive.log)

**Comment by herve-er** [comment] 2024-09-17 14:33
Hello,

Regarding the "Unable to open parameters database" error, a workaround is available here: https://github.com/Infomaniak/desktop-kDrive/issues/268#issuecomment-2355615630. Please let us know if the issue persists after following these steps.

----

@pascalm7,

Unfortunately, we do not have much insight into the cause of the crash from the logs. Could you please check in the system monitor to see if there are any kDrive instances running in the background? If so, you can kill them and verify that they do not automatically restart. If they do, kill them again and they should not restart. Once you have done this, delete /home/.config/kDrive again (there is no need to delete kDrive-logdir). You can now try to start the AppImage again.

Let us know if the "kDrive application closing due to a fatal error" issue still persists.

----

**Comment by pascalm7** [comment] 2024-09-19 14:43
@herve-er
Thanks for your help. Yes, I did check that no other process was running when the appimage was launched but the error persists.
Here is the cmd line output:
`pascalm@gatta:~$ ~/AppImages/kdrive.appimage --version
kDrive server starting
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
kDrive version 3.6.4 (build 20240814)
Using Qt 6.2.3, built against Qt 6.2.3
Using 'OpenSSL 1.1.1f  31 Mar 2020'
`
`pascalm@gatta:~$ ~/Téléchargements/kDrive-3.6.4.20240814-amd64.AppImage
kDrive server starting
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
log4cplus:ERROR file is not open: /tmp/kDrive-logdir/20240919_1633_kDrive.log
log4cplus:ERROR No appenders could be found for logger (Main).
log4cplus:ERROR Please initialize the log4cplus system properly.
`
![Capture d’écran du 2024-09-19 16-40-32](https://github.com/user-attachments/assets/eafcb4de-2588-416b-9598-e030db8870da)

I hope that helps.

**Comment by herve-er** [comment] 2024-09-20 13:39
@pascalm7 
It seems that your tmp directory is full (as indicated by the error message: log4cplus:ERROR file is not open: /tmp/kDrive-logdir/20240919_1633_kDrive.log). Since AppImages are extract in /tmp and then run from there, it's possible that the AppImage cannot be fully extract, leading to these crashes.

To verify if this hypothesis is correct, please try extracting the AppImage using the following command:
./kDrive-3.6.4.20240814-amd64.AppImage --appimage-extract

This will create a new folder named squashfs-root alongside the kDrive AppImage. Inside the squashfs-root folder, navigate to squashfs-root/usr/bin, and from here, run ./kDrive.

If the application starts successfully, it's highly likely that the issue is due to insufficient space in your tmp directory.

**Comment by pascalm7** [comment] 2024-09-20 15:21
Same error "kDrive application closing due to a fatal error"
```
pascalm@gatta:~/Téléchargements/squashfs-root/usr/bin$ ./kDrive
kDrive server starting
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
log4cplus:ERROR file is not open: /tmp/kDrive-logdir/20240920_1636_kDrive.log
log4cplus:ERROR No appenders could be found for logger (Main).
log4cplus:ERROR Please initialize the log4cplus system properly.
```
tmpfs size:
```
pascalm@gatta:~/Téléchargements/squashfs-root/usr/bin$ df -h
Filesystem                                        Size  Used Avail Use% Mounted on
tmpfs                                             6.2G  6.6M  6.2G   1% /run
/dev/mapper/keystore-rpool                        437M   28K  404M   1% /run/keystore/rpool
rpool/ROOT/ubuntu_woks98                          144G  5.2G  139G   4% /
tmpfs                                              31G  4.0K   31G   1% /dev/shm
tmpfs                                             5.0M   16K  5.0M   1% /run/lock
efivarfs                                          248K   42K  202K  18% /sys/firmware/efi/efivars
rpool/USERDATA/pascalm_0spfd9                     890G  752G  139G  85% /home/pascalm
rpool/ROOT/ubuntu_woks98/srv                      139G  256K  139G   1% /srv
rpool/USERDATA/root_0spfd9                        139G   66M  139G   1% /root
rpool/ROOT/ubuntu_woks98/var/lib                  158G   20G  139G  13% /var/lib
rpool/ROOT/ubuntu_woks98/usr/local                139G  640K  139G   1% /usr/local
rpool/ROOT/ubuntu_woks98/var/games                139G  256K  139G   1% /var/games
rpool/ROOT/ubuntu_woks98/var/log                  139G   71M  139G   1% /var/log
rpool/ROOT/ubuntu_woks98/var/mail                 139G  256K  139G   1% /var/mail
rpool/ROOT/ubuntu_woks98/var/spool                139G  5.0M  139G   1% /var/spool
rpool/ROOT/ubuntu_woks98/var/snap                 139G   15M  139G   1% /var/snap
rpool/ROOT/ubuntu_woks98/var/www                  139G  256K  139G   1% /var/www
rpool/ROOT/ubuntu_woks98/var/lib/NetworkManager   139G  1.0M  139G   1% /var/lib/NetworkManager
rpool/ROOT/ubuntu_woks98/var/lib/AccountsService  139G  256K  139G   1% /var/lib/AccountsService
rpool/ROOT/ubuntu_woks98/var/lib/apt              139G  107M  139G   1% /var/lib/apt
rpool/ROOT/ubuntu_woks98/var/lib/dpkg             139G  101M  139G   1% /var/lib/dpkg
bpool/BOOT/ubuntu_woks98                          1.8G  184M  1.6G  11% /boot
/dev/nvme0n1p1                                    511M   15M  497M   3% /boot/efi
tmpfs                                             6.2G  2.6M  6.2G   1% /run/user/1000
```
Maybe something to do wit AppArmor? Anyone know how to temporarily disable AppArmor in order to troubleshoot the issue?
```
pascalm@gatta:~/Téléchargements/squashfs-root/usr/bin$ tail -f /var/log/syslog
...
2024-09-20T17:10:43.808734+02:00 gatta kernel: audit: type=1400 audit(1726845043.803:1769): apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=37568 comm="kDrive_client" requested="userns_create" denied="userns_create"
2024-09-20T17:10:43.808754+02:00 gatta kernel: traps: kDrive_client[37568] trap int3 ip:70c597b7e604 sp:7ffd0aa125e0 error:0 in libQt6WebEngineCore.so.6[70c594533000+8b3e000]
2024-09-20T17:10:44.904429+02:00 gatta ubuntu-appindicators@ubuntu.com[7334]: Could not get menu properties menu proxy: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
2024-09-20T17:10:45.152699+02:00 gatta kernel: audit: type=1400 audit(1726845045.143:1770): apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=37601 comm="kDrive_client" requested="userns_create" denied="userns_create"
2024-09-20T17:10:45.152729+02:00 gatta kernel: traps: kDrive_client[37601] trap int3 ip:78c6f1d1a604 sp:7ffc7d5e4d30 error:0 in libQt6WebEngineCore.so.6[78c6ee6cf000+8b3e000]
2024-09-20T17:10:46.412014+02:00 gatta gnome-shell[7334]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x800008 specified for 0x800006.
2024-09-20T17:10:46.428060+02:00 gatta gnome-shell[7334]: [tilingshell] [extension] building a tiling manager for each monitor
...
```

**Comment by herve-er** [comment] 2024-09-23 12:00
@pascalm7,

It appears that you've identified the cause of the issue:
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844

Could you please let us know which version of AppArmor you are using by running `dpkg -l apparmor`?

After that, could you try upgrading your packages with `sudo apt upgrade` and let us know if AppArmor still denies access? 

According to their changelog, this issue seems to have been fixed in : [4.0.1really4.0.1-0ubuntu0.24.04.3](https://launchpad.net/ubuntu/+source/apparmor/4.0.1really4.0.1-0ubuntu0.24.04.3).

**Comment by pascalm7** [comment] 2024-09-23 14:38
Good spot! Apparmor prior to upgrade:
```
pascalm@gatta:~$ dpkg -l apparmor
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                           Architecture Description
+++-==============-=================================-============-======================================
ii  apparmor       4.0.1really4.0.1-0ubuntu0.24.04.3 amd64        user-space parser utility for AppArmor
```

After the upgrade:
```
pascalm@gatta:~$ dpkg -l apparmor
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                           Architecture Description
+++-==============-=================================-============-======================================
ii  apparmor       4.0.1really4.0.1-0ubuntu0.24.04.3 amd64        user-space parser utility for AppArmor
```
Unfortunately, kDrive still closes with a fatal error, apparmor complains with a different error message this time:
```
...
2024-09-23T16:06:36.650916+02:00 gatta kernel: audit: type=1400 audit(1727100396.646:349): apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=7822 comm="kDrive_client" requested="userns_create" denied="userns_create"
2024-09-23T16:06:36.650934+02:00 gatta kernel: traps: kDrive_client[7822] trap int3 ip:7933c9ff0604 sp:7ffd72ede210 error:0 in libQt6WebEngineCore.so.6[7933c69a5000+8b3e000]
2024-09-23T16:06:37.014929+02:00 gatta kernel: audit: type=1400 audit(1727100397.010:350): apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=7852 comm="kDrive_client" requested="userns_create" denied="userns_create"
2024-09-23T16:06:37.014951+02:00 gatta kernel: traps: kDrive_client[7852] trap int3 ip:7b3025df0604 sp:7ffd07e702e0 error:0 in libQt6WebEngineCore.so.6[7b30227a5000+8b3e000]
2024-09-23T16:06:37.229029+02:00 gatta gnome-shell[4830]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x800008 specified for 0x800006.
2024-09-23T16:06:39.372470+02:00 gatta systemd[1]: tmp-.mount_kdriveKnvtwT.mount: Deactivated successfully.
...
```

**Comment by pascalm7** [comment] 2024-09-23 15:13
I went a bit further, I hope it helps.
As instructed in https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844/comments/148 I installed the backported apparmor available here: https://launchpad.net/~apparmor-dev/+archive/ubuntu/apparmor-backports with
```
sudo add-apt-repository ppa:apparmor-dev/apparmor-backports
sudo apt update
sudo apt full-upgrade
sudo apt install apparmor-notify
```
Then launched 
```
pascalm@gatta:~/AppImages$ aa-notify -p -s1 --prompt-filter=userns
Notification emitter started in the background
pascalm@gatta:~/AppImages$ ./kdrive.appimage 
kDrive server starting
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
log4cplus:ERROR file is not open: /tmp/kDrive-logdir/20240923_1648_kDrive.log
log4cplus:ERROR No appenders could be found for logger (Main).
log4cplus:ERROR Please initialize the log4cplus system properly.
```
I got the following error messages:

![Capture d’écran du 2024-09-23 17-00-28](https://github.com/user-attachments/assets/0a2c3a21-e72f-48f2-9aff-48d74fcddb93)


I would appreciate any help on how to create an apparmor profile for `kDrive_client`.

**Comment by pascalm7** [comment] 2024-09-25 10:49
Just in case it would help anyone, I found this dirty workaround:

Edited the file `/etc/apparmor.d/kdrive` with the the following content:
```
# This profile allows everything and only exists to give the
# application a name instead of having the label "unconfined"

abi <abi/4.0>,
include <tunables/global>

profile kdrive /home/pascalm/AppImages/kdrive.appimage flags=(unconfined) {
  userns,
  
  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/kdrive>
}
```
Restarted apparmor with `sudo service apparmor restart`

**Comment by herve-er** [comment] 2024-09-30 08:57
@pascalm7 Thank you and great job on this workaround! 
We will look into this matter on our end to find a suitable solution to prevent being blocked due to this recent increase in AppArmor restrictions  (without user action).

**Closed** 2024-09-30 10:05 UTC
Labels: bug
