### ISSUE TITLE
Kdrive uses all available space

### ISSUE THREAD

**Issue by beankylla** [Infomaniak/desktop-kDrive#328] opened 2024-09-28 11:52 UTC
*Note: Please write your issue only in english*

**Description**
Appimage uses /tmp folder until it's full and then pauses the sync. You need to reboot or empty /tmp folder to resume sync

**Steps to reproduce**
Kdrive Appimage running on Fedora 40
While syncing data, kdrive will constantly increase the amount of /tmp space used. 
default /tmp in fedora is 8 gigs so when they are full this stalls the sync process
after removing the /tmp and using / where there was ~35 gigs available Kdrive filled all of the space 

**Expected behavior**
Tmp space should be freed after being used

**Screenshots**
![image](https://github.com/user-attachments/assets/d8695858-71c2-481e-bb28-7721646f9b4a)
![image](https://github.com/user-attachments/assets/9995bca2-8be0-4d55-b4ca-8aa41a9e3c79)
![image](https://github.com/user-attachments/assets/b73eded3-72ee-4ef9-864e-4473cd11edf4)

**Logs**
"Open debugging folder" in "Preferences"
Not sure my logs are relevant here, i'm using the app in a really standard way
*Please note that the name of your files will appear in this log.*

**Additional context**

**Comment by herve-er** [comment] 2024-09-30 09:50
Hello @beankylla,
Thank you for the report.
This seems to be the same issue as https://github.com/Infomaniak/desktop-kDrive/issues/204

After investigation, there is currently a bug where files are not removed from tmp when tmp is on a different file system than the synchronization. It is typically the case on Linux distributions that set the /tmp on RAM.

I have raised the priority of this issue in our roadmap for it to be fixed in the next release (Unfortunately not in 3.6.6 as it is already in its release process).

**Comment by herve-er** [comment] 2024-09-30 10:08
I will close this issue as it is a duplicate of https://github.com/Infomaniak/desktop-kDrive/issues/204, but please feel free to respond to the original issue at https://github.com/Infomaniak/desktop-kDrive/issues/204 or to reopen this one if you believe it is necessary for any reason.

**Closed by herve-er** 2024-09-30 10:08 UTC
Labels: bug
